language: java
os: linux
dist: xenial


jdk:
    - openjdk11

install: true

addons:
  sonarcloud:
    organization: "d0543027"
    token:
      secure: $SONAR_TOKEN

script:
    - gradle jacocoTestReport
    - gradle sonarqube -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASSWORD -Dsonar.projectKey=$SONAR_PROJECT_KEY
